import type { AppProps } from 'next/app';
import Head from 'next/head';

import { createGlobalStyle, ThemeProvider } from 'styled-components';

const GlobalStyle = createGlobalStyle`
html,
body {
  padding: 0;
  margin: 0;
  background: #000;
}

a {
  color: inherit;
  text-decoration: none;
}

* {
  box-sizing: border-box;
}
`;

const theme = {
	// Colors
	black: `#0B0D17`,
	purple: '#D0D6F9',
	grey: '#979797',
	white: '#FFFFFF',

	//Fonts
	bellefair: "'Bellefair', serif",
	barlow: "'Barlow Condensed', sans-serif",
};

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>New App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon-32x32.ico' />
			</Head>
			<ThemeProvider theme={theme}>
				<GlobalStyle />
				<Component {...pageProps} />
			</ThemeProvider>
		</>
	);
}

export default MyApp;
